---
title: "New Zealand's COVID-19 testing"
author: "Minh Chau Van Nguyen"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
runtime: shiny
---




```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(highcharter)
library(plyr)
library(readxl)
library(dplyr)
library(flexdashboard)

# Make some noisily increasing data
set.seed(955)
dat <- data.frame(cond = rep(c("A", "B"), each=10),
                  xvar = 1:20 + rnorm(20,sd=3),
                  yvar = 1:20 + rnorm(20,sd=3))

fake_dt <- read_excel("Analyst_Lab_Data 2.xls")
true_dt <- read_excel("Population_Data 2.xls")
names(true_dt)[2] <- "SA22018_V1_00"

# excluding those that replied "Unknown" for Ethnicity, n = 1656 observations
dd <- merge(fake_dt, true_dt, by = c("SA22018_V1_00", "Ethnicity"))
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
selectInput(inputId = "Location", 
            label = h3("Terriotal Authority"), 
            choices = unique(factor(dd$TA2018_V1_00_NAME)))

loca <- reactive(input$Location)
```

Microarray data matrix for 80 experiments with Saccharomyces Cerevisiae
organism extracted from R's `biclust` package.

Sebastian Kaiser, Rodrigo Santamaria, Tatsiana Khamiakova, Martin Sill, Roberto
  Theron, Luis Quintales, Friedrich Leisch and Ewoud De Troyer. (2015). biclust:
  BiCluster Algorithms. R package version 1.2.0.
  http://CRAN.R-project.org/package=biclust

Row
-----------------------------------------------------------------------

### Scatter Chart with geom_point 

```{r}
renderHighchart({
  new <- dd[dd$TA2018_V1_00_NAME == loca(),]
  data <- new[names(new) %in% c("Ethnicity", "SA22018_V1_00_NAME", "Number_of_Tests", "SA2_average_NZDep2018", "Census_2019_Population_Estimate")]
  names(data)[c(2,5)] <- c("NZDep", "Population")
  
  data$Ethnicity <- factor(data$Ethnicity)
  levels(data$Ethnicity) <- c("Asian", "M훮ori", "Other", "Pacific")
  data$Ethnicity <- factor(data$Ethnicity, levels = c("M훮ori", "Pacific", "Asian", "Other"))
  
  data <- with(data, data[order(Ethnicity, SA22018_V1_00_NAME, Number_of_Tests, NZDep, Population),])
  
  data$SA22018_V1_00_NAME <- factor(data$SA22018_V1_00_NAME)
  
  hc <- highchart() %>%
  hc_chart(type = "column") %>%
  hc_yAxis(title = list(text = "Number of tests per day", style = list(fontWeight = 'bold'))) %>%
  hc_xAxis(categories = levels(data$Ethnicity), title = list(text = "Priotised Ethnicity group", style = list(fontWeight = 'bold'))) %>%
  hc_plotOptions(column = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal",
    borderColor = "#5ab1ef",
    borderWidth = 2,
    enableMouseTracking = TRUE))

for(lvl in levels(data$SA22018_V1_00_NAME)){
  dt <- data[data$SA22018_V1_00_NAME == lvl, ][,4]
  hc <- hc_add_series(hc, data = dt, name = lvl)
}

hc %>% hc_chart(inverted = TRUE) %>%
  hc_tooltip(formatter= JS("function () { 
  return '<b>Area: </b>' + this.series.name  + 
  ' <br /> <b>Number of tests:</b> ' + this.point.y + ' tests' + 
  '<br /> <b>Population:</b> ' + this.point.Population +
  '<br /> <b>NZ Deprivation Index:</b> ' + this.point.NZDep;}"))
})
```


Row
-----------------------------------------------------------------------

### Scatter Chart with geom_point

```{r}
renderHighchart({
  new <- dd[dd$TA2018_V1_00_NAME == loca(),]
  data <- new[names(new) %in% c("Ethnicity", "SA22018_V1_00_NAME", "Number_of_Tests", "SA2_average_NZDep2018", "Census_2019_Population_Estimate")]
  names(data)[c(2,5)] <- c("NZDep", "Population")
  
  data$Ethnicity <- factor(data$Ethnicity)
  levels(data$Ethnicity) <- c("Asian", "M훮ori", "Other", "Pacific")
  data$Ethnicity <- factor(data$Ethnicity, levels = c("M훮ori", "Pacific", "Asian", "Other"))
  
  data <- with(data, data[order(Ethnicity, SA22018_V1_00_NAME, Number_of_Tests, NZDep, Population),])
  
  data$SA22018_V1_00_NAME <- factor(data$SA22018_V1_00_NAME)
  
  hc <- highchart() %>%
  hc_chart(type = "column") %>%
  hc_yAxis(title = list(text = "Number of tests per day", style = list(fontWeight = 'bold'))) %>%
  hc_xAxis(categories = levels(data$Ethnicity), title = list(text = "Priotised Ethnicity group", style = list(fontWeight = 'bold'))) %>%
  hc_plotOptions(column = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal",
    borderColor = "#5ab1ef",
    borderWidth = 2,
    enableMouseTracking = TRUE))

for(lvl in levels(data$SA22018_V1_00_NAME)){
  dt <- data[data$SA22018_V1_00_NAME == lvl, ][,4]
  hc <- hc_add_series(hc, data = dt, name = lvl)
}

hc %>% hc_chart(inverted = TRUE) %>%
  hc_tooltip(formatter= JS("function () { 
  return '<b>Area: </b>' + this.series.name  + 
  ' <br /> <b>Number of tests:</b> ' + this.point.y + ' tests' + 
  '<br /> <b>Population:</b> ' + this.point.Population +
  '<br /> <b>NZ Deprivation Index:</b> ' + this.point.NZDep;}"))
})
```


