---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(readxl)
library(echarts4r)
library(highcharter)
library(dplyr)

fake_dt <- read_excel("Analyst_Lab_Data 2.xls")
true_dt <- read_excel("Population_Data 2.xls")
names(true_dt)[2] <- "SA22018_V1_00"

# excluding those that replied "Unknown" for Ethnicity, n = 1656 observations
dd <- merge(fake_dt, true_dt, by = c("SA22018_V1_00", "Ethnicity"))


new <- dd[dd$TA2018_V1_00_NAME == "Far North District",]

new$Ethnicity <- factor(new$Ethnicity, levels = c("Asian", "Maori", "Other", "Pacific"))
levels(new$Ethnicity) <- c("Maori", "Pacific", "Asian", "Other")
#levels(new$Ethnicity)

data <- new %>% top_n(15, Number_of_Tests)

hc <- highchart() %>%
  hc_chart(type = "column", height = 350, width = 400) %>%
  hc_yAxis(title = list(text = "No.of.cases", style = list(fontWeight = 'bold'))) %>%
  hc_xAxis(categories = data$Ethnicity, title = list(text = "Age group", style = list(fontWeight = 'bold'))) %>%
  hc_plotOptions(column = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal",
    borderColor = "#5ab1ef",
    borderWidth = 2,
    enableMouseTracking = TRUE)
  )
```



```{r}
hc <- highchart() %>%
  hc_chart(type = "column", height = 350, width = 400) %>%
  hc_yAxis(title = list(text = "No.of.cases", style = list(fontWeight = 'bold'))) %>%
  hc_xAxis(categories = data$Ethnicity, title = list(text = "Age group", style = list(fontWeight = 'bold'))) %>%
  hc_plotOptions(column = list(
    dataLabels = list(enabled = FALSE),
    stacking = "normal",
    borderColor = "#5ab1ef",
    borderWidth = 2,
    enableMouseTracking = TRUE)
  )
hc
```


